version: '3.4'
services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: masgruas_production
      POSTGRES_USER: masgruas
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      SECRET_KEY:
      PG_PASSWORD: postgres
    volumes:
      - .:/massgruas
    ports:
      - "80:3000"
    env_file: .env
    depends_on:
      - db

volumes:
  data:
